### ISSUE TITLE
Archive release to Zenodo

### ISSUE THREAD

**Issue by pierrepo** [IFB-ElixirFr/katacoda-scenarios#31]
We can automate integration between Zenodo and GitHub: https://guides.github.com/activities/citable-code/

To ease the process of automatically archiving releases in Zenodo, we can create a `.zenodo.json` file (for instance like [this one](https://github.com/patrickfuchs/buildH/blob/master/.zenodo.json)). 

In this perspective, I need your ORCID. Could provide them in a comment of this issue?

**Comment by olisand** [comment]
0000-0003-1465-1640

**Comment by pierrepo** [comment]
Gildas Le Corguillé : 0000-0003-1742-9711

**Comment by clairetn** [comment]
Claire Toffano-Nioche : 0000-0003-4134-6844

**Comment by julozi** [comment]
Julien Seiler : 0000-0002-4549-5188

**Comment by dputhier** [comment]
D Puthier: 0000-0002-7240-5280

**Comment by pierrepo** [comment]
@hchiapello can you please add your ORCID?

**Comment by pierrepo** [comment]
@thomasdenecker can you please add your ORCID?

**Comment by thomasdenecker** [comment]
Thomas Denecker : [0000-0003-1421-7641](https://orcid.org/0000-0003-1421-7641)

**Comment by pierrepo** [comment]
Hélène Chiapello : 0000-0001-5102-0632
